"""Add pad_len field

Revision ID: 195f1c98dcf4
Revises: 2e2e7306d529
Create Date: 2025-07-14 08:47:57.682641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195f1c98dcf4'
down_revision: Union[str, None] = '2e2e7306d529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('figures_name_key'), 'figures', schema='figure', type_='unique')
    op.add_column('type_of_collect', sa.Column('pad_len', sa.Integer(), nullable=False), schema='figure')
    op.create_unique_constraint(None, 'type_of_collect', ['pad_len'], schema='figure')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'type_of_collect', schema='figure', type_='unique')
    op.drop_column('type_of_collect', 'pad_len', schema='figure')
    op.create_unique_constraint(op.f('figures_name_key'), 'figures', ['name'], schema='figure', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
