"""Initial commit

Revision ID: 26512e77ab8f
Revises:
Create Date: 2025-07-15 20:07:35.436115
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26512e77ab8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("SET search_path TO figure; CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA figure;")

    op.create_table(
        'type_of_collect',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('article', sa.String(), nullable=False),
        sa.Column('pad_len', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('article'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('pad_len'),
        schema='figure'
    )
    op.create_table(
        'figures',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('bricklink_id', sa.String(), nullable=False),
        sa.Column('type_collected_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['type_collected_id'], ['figure.type_of_collect.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('bricklink_id'),
        schema='figure'
    )
    op.create_index(
        op.f('ix_figure_figures_id'),
        'figures',
        ['id'],
        unique=False,
        schema='figure'
    )

    # Добавляем GIN‑индекс на name с триграммами
    op.create_index(
        'ix_figures_name_trgm',
        'figures',
        ['name'],
        schema='figure',
        postgresql_using='gin',
        postgresql_ops={'name': 'gin_trgm_ops'},
    )

    op.create_table(
        'figure_to_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('price_buy', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('price_sale', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('buy_date', sa.Date(), nullable=True),
        sa.Column('sale_date', sa.Date(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('figure_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['figure_id'], ['figure.figures.id']),
        sa.PrimaryKeyConstraint('id'),
        schema='figure'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Удаляем индекс
    op.drop_index('ix_figures_name_trgm', table_name='figures', schema='figure')

    # Откатываем всё остальное
    op.drop_table('figure_to_user', schema='figure')
    op.drop_index(op.f('ix_figure_figures_id'), table_name='figures', schema='figure')
    op.drop_table('figures', schema='figure')
    op.drop_table('type_of_collect', schema='figure')

