"""aa

Revision ID: 6ef1cd44e5a6
Revises: 26512e77ab8f
Create Date: 2025-07-23 12:25:53.109267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef1cd44e5a6'
down_revision: Union[str, None] = '26512e77ab8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_figures_name_trgm'), table_name='figures', schema='figure', postgresql_using='gin')
    op.drop_constraint(op.f('type_of_collect_pad_len_key'), 'type_of_collect', schema='figure', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('type_of_collect_pad_len_key'), 'type_of_collect', ['pad_len'], schema='figure', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_figures_name_trgm'), 'figures', ['name'], unique=False, schema='figure', postgresql_using='gin')
    # ### end Alembic commands ###
