"""Initial migration

Revision ID: e884c45fedd8
Revises: 
Create Date: 2025-07-11 22:37:57.957530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e884c45fedd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_of_collect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='figure'
    )
    op.create_table('figures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bricklink_id', sa.String(), nullable=False),
    sa.Column('type_collected_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_collected_id'], ['figure.type_of_collect.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bricklink_id'),
    sa.UniqueConstraint('name'),
    schema='figure'
    )
    op.create_index(op.f('ix_figure_figures_id'), 'figures', ['id'], unique=False, schema='figure')
    op.create_table('figure_to_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_buy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_sale', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('buy_date', sa.Date(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('figure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['figure_id'], ['figure.figures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='figure'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('figure_to_user', schema='figure')
    op.drop_index(op.f('ix_figure_figures_id'), table_name='figures', schema='figure')
    op.drop_table('figures', schema='figure')
    op.drop_table('type_of_collect', schema='figure')
    # ### end Alembic commands ###
